spring.application.name=agendador-tarefas

# Fallback para o MongoDB: Se não houver variável, usa localhost
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db_agendador}

usuario.url=${USUARIO_URL:http://localhost:8081/usuario}

server.port=8082

